[package]
name = "rooster"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
borsh = "0.9.3"
mpl-token-metadata = { path = "../../metaplex-program-library/token-metadata/program", features = ["no-entrypoint"] }
mpl-utils = "0.0.5"
num-derive = "0.3.3"
num-traits = "~0.2"
shank = "0.0.10"
solana-program = "1.13.5"
thiserror = "~1.0"


[features]
no-entrypoint = []
test-bpf = []

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "1.13.5"
solana-sdk = "1.13.5"
solana-logger = "1.13.5"

[lib]
crate-type = ["cdylib", "lib"]
